# Generated by Django 5.2.4 on 2025-09-19 13:36

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio of the author')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('mastodon', models.CharField(blank=True, max_length=100)),
                ('discord', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(help_text='Date when the post was published', verbose_name='Post date')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief description of the post', max_length=500)),
                ('header_image', models.ImageField(blank=True, help_text='Featured image for the post', null=True, upload_to='blog/headers/')),
                ('header_image_alt', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('enable_comments', models.BooleanField(default=False, help_text='Show comments section on this post')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='publications.author')),
            ],
            options={
                'verbose_name': 'Blog Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='publications.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='publications.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(help_text='Date when the event was announced', verbose_name='Post date')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief description of the event', max_length=500)),
                ('header_image', models.ImageField(blank=True, help_text='Featured image for the event', null=True, upload_to='events/headers/')),
                ('header_image_alt', models.CharField(blank=True, help_text='Alt text for the header image', max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('enable_comments', models.BooleanField(default=False, help_text='Show comments section on this event')),
                ('start_date', models.DateField(help_text='Date when the event starts', verbose_name='Event start date')),
                ('end_date', models.DateField(blank=True, help_text='Date when the event ends (optional)', null=True, verbose_name='Event end date')),
                ('location', models.CharField(blank=True, help_text='Where the event takes place', max_length=255)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('webinar', 'Webinar'), ('conference', 'Conference'), ('meetup', 'Meetup'), ('other', 'Other')], default='other', help_text='Type of event', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='publications.author')),
            ],
            options={
                'verbose_name': 'Event Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='publications.eventpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='publications.EventPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
