# Generated by Django 5.2.4 on 2025-09-24 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_blogindexpage_eventindexpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventindexpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="BlogIndexPage",
        ),
        migrations.DeleteModel(
            name="EventIndexPage",
        ),
    ]
